// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4-tFgogV6-G2C1LHXQtpl5O9eFdK92Ko',
    appId: '1:970507363588:web:14b99a055633b8a0e1dc51',
    messagingSenderId: '970507363588',
    projectId: 'grab-n-grub-81ed1',
    authDomain: 'grab-n-grub-81ed1.firebaseapp.com',
    storageBucket: 'grab-n-grub-81ed1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF7ypa_nU3oX5MnWB9iDM2SG3DOQwyueE',
    appId: '1:970507363588:android:736b4ca89fffd510e1dc51',
    messagingSenderId: '970507363588',
    projectId: 'grab-n-grub-81ed1',
    storageBucket: 'grab-n-grub-81ed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV67yjta6InrIGDQHZ8gDffwQGpYex-L8',
    appId: '1:970507363588:ios:a45fc5e4cae109a2e1dc51',
    messagingSenderId: '970507363588',
    projectId: 'grab-n-grub-81ed1',
    storageBucket: 'grab-n-grub-81ed1.appspot.com',
    iosBundleId: 'com.example.gngSeller',
  );

}